[[redirects]]
    from = "/"
    to = "/fr"
    status = 302
    force = true
    query = {path = ":path"}
    conditions = {Language = ["fr"]}

[[redirects]]
    from = "/"
    to = "/en"
    status = 302
    force = true
    query = {path = ":path"}
